print(bool[10])
print(bool[10.10])
print(bool[1+0j])
print(bool[0+10j])
print(bool(True))
print(bool(False))
print(bool(1))
print(bool(0))
print(bool(-1))
print(bool(100))
print(bool(10.5))
print(bool(0.0))
print(bool(-5.7))
print(bool(1+2j))
print(bool(0+0j))
print(bool("Python"))
print(bool(""))
print(bool(" "))
print(bool([1, 2, 3]))
print(bool([]))
print(bool((1, 2)))
print(bool(()))
print(bool({1, 2, 3}))
print(bool(set()))
print(bool({"a": 1}))
print(bool({}))
print(bool(None))